### ISSUE TITLE
data.status.measurements.mileageKm is not reliable 

### ISSUE THREAD

**Issue by Bramke95** [Hamster128/CarApp#1]
Since yesterday data.status.measurements.mileageKm is not returning anything anymore. I presume this value has been move to another location. Also sometimes the measurements field itself is not returned.

**Comment by Hamster128** [comment]
This happens from time to time, the vw servers are not very reliable, even the original Cupra app has currently problems showing the milage. I think it will come back.

**Comment by Hamster128** [comment]
Hi, the mileage came back, but you were right they moved it, update commited.
